/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'background':               '#111319',
        'surface':                  '#111319',
        'surface-dim':              '#111319',
        'surface-container-lowest': '#0c0e14',
        'surface-container-low':    '#191b22',
        'surface-container':        '#1e1f26',
        'surface-container-high':   '#282a30',
        'surface-container-highest':'#33343b',
        'surface-bright':           '#373940',
        'surface-variant':          '#33343b',
        'on-background':            '#e2e2eb',
        'on-surface':               '#e2e2eb',
        'on-surface-variant':       '#c7c4d7',
        'outline':                  '#908fa0',
        'outline-variant':          '#464554',
        'primary':                  '#c0c1ff',
        'on-primary':               '#1000a9',
        'primary-fixed':            '#e1e0ff',
        'primary-fixed-dim':        '#c0c1ff',
        'on-primary-fixed':         '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'primary-container':        '#8083ff',
        'on-primary-container':     '#0d0096',
        'inverse-primary':          '#494bd6',
        'secondary':                '#c4c6d0',
        'on-secondary':             '#2d3038',
        'secondary-fixed':          '#e0e2ec',
        'secondary-fixed-dim':      '#c4c6d0',
        'on-secondary-fixed':       '#191c22',
        'on-secondary-fixed-variant':'#44474e',
        'secondary-container':      '#464951',
        'on-secondary-container':   '#b6b8c1',
        'tertiary':                 '#4ae176',
        'on-tertiary':              '#003915',
        'tertiary-fixed':           '#6bff8f',
        'tertiary-fixed-dim':       '#4ae176',
        'on-tertiary-fixed':        '#002109',
        'on-tertiary-fixed-variant':'#005321',
        'tertiary-container':       '#00a74b',
        'on-tertiary-container':    '#003111',
        'error':                    '#ffb4ab',
        'on-error':                 '#690005',
        'error-container':          '#93000a',
        'on-error-container':       '#ffdad6',
        'surface-tint':             '#c0c1ff',
        'inverse-surface':          '#e2e2eb',
        'inverse-on-surface':       '#2e3037',
        'indigo':                   '#6366F1',
        'amber':                    '#F59E0B',
      },
      fontFamily: {
        sans:     ['Outfit', 'Inter', 'ui-sans-serif', 'system-ui'],
        headline: ['Outfit'],
        body:     ['Inter'],
        label:    ['Outfit'],
        mono:     ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:  '0.25rem',
        md:  '0.375rem',
        lg:  '0.5rem',
        xl:  '0.75rem',
        full:'9999px',
      },
    },
  },
  plugins: [],
}
